version: '3.8'

services:
  app:
    container_name: NestApp
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
